import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from "@clerk/ui/themes";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "chefGPT- Ai Recipe platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        theme: neobrutalism,
      }}
    >
      <html lang="en" suppressHydrationWarning={true}>
        <body className={`${inter.className}`}>
          <Header />
          <main className="min-h-screen">{children}</main>
          <footer className="py-8 px-4 border-t ">
            <div
              className="max-w-6xl mx-auto flex justify-center
         items-center "
            >
              <p className="text-stone-500 text-sm">Made By Sonal10Dev</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
